from typing import Protocol
from .models import *
class Agent(Protocol):
    manifest:AgentManifest
    def discover(self,request:AgentRequest):...
    def plan(self,request:AgentRequest)->AgentPlan:...
    def execute(self,plan:AgentPlan,context:AgentContext)->AgentExecutionResult:...
    def verify(self,execution:AgentExecutionResult,context:AgentContext)->AgentVerificationResult:...
    def learn(self,outcome:AgentOutcome,context:AgentContext)->LearningProposal:...
class AgentDefaults:
    def discover(self,request):return {"accepted":request.requested_capability in self.manifest.capabilities}
    def learn(self,outcome,context):return LearningProposal()

